DECLARE @DFECHADESDE AS DATETIME, @DFECHAHASTA AS DATETIME
DECLARE @VTIEMPO VARCHAR(100), @VTIEMPOSEM VARCHAR(100), @VTIEMPODIA VARCHAR(100), @VTIEMPOHOR VARCHAR(100)
SET @DFECHADESDE = GETDATE()
SET @DFECHAHASTA = DATEADD(HOUR, 100, GETDATE())
SELECT @DFECHADESDE = [FechaDesde], @DFECHAHASTA = [FechaHasta] FROM [DemoAlquileresMVC].[dbo].[alquiler] WHERE ID = 4

DECLARE @INUMERO INT, @ITIEMPOHOR INT, @ITIEMPODIA INT, @ITIEMPOSEM INT
DECLARE @NTIEMPO NUMERIC(19,2), @NTIEMPOHOR NUMERIC(19,2), @NTIEMPODIA NUMERIC(19,2), @NTIEMPOSEM NUMERIC(19,2)
DECLARE @NPRECIO NUMERIC(19,2), @NPRECIOHOR NUMERIC(19,2), @NPRECIODIA NUMERIC(19,2), @NPRECIOSEM NUMERIC(19,2)

		SET @ITIEMPOHOR = DATEDIFF(HOUR, @DFECHADESDE,@DFECHAHASTA) - CASE WHEN DATEADD(HOUR, DATEDIFF(HOUR, @DFECHADESDE, @DFECHAHASTA), @DFECHADESDE) > @DFECHAHASTA THEN 1 ELSE 0 END
		SET @ITIEMPODIA = DATEDIFF(DAY, @DFECHADESDE,@DFECHAHASTA) - CASE WHEN DATEADD(DAY, DATEDIFF(DAY, @DFECHADESDE, @DFECHAHASTA), @DFECHADESDE) > @DFECHAHASTA THEN 1 ELSE 0 END
		SET @ITIEMPOSEM = DATEDIFF(WEEK, @DFECHADESDE,@DFECHAHASTA) - CASE WHEN DATEADD(WEEK, DATEDIFF(WEEK, @DFECHADESDE, @DFECHAHASTA), @DFECHADESDE) > @DFECHAHASTA THEN 1 ELSE 0 END
		
		SET @NTIEMPO = @ITIEMPOHOR / 24.00 
		SELECT @NTIEMPO, @ITIEMPODIA
		IF @NTIEMPO >= 1
			BEGIN
				SET @NTIEMPOHOR = @NTIEMPO - @ITIEMPODIA
				SET @NTIEMPOHOR = @NTIEMPOHOR * 24.00
				SET @NTIEMPO = @ITIEMPODIA / 7.00

				IF @NTIEMPO >= 1
					BEGIN
						SET @NTIEMPODIA = @NTIEMPO - @ITIEMPOSEM
						SET @NTIEMPODIA = @NTIEMPODIA * 7.00
						SET @NTIEMPOSEM = @ITIEMPOSEM
						SET @NTIEMPOHOR = ROUND(@NTIEMPOHOR, 0)
					END
				ELSE
					BEGIN
						SET @NTIEMPOSEM = @NTIEMPO
						SET @NTIEMPODIA = @ITIEMPODIA
						SET @NTIEMPOHOR = ROUND(@NTIEMPOHOR, 0)
					END
			END
		ELSE
			BEGIN
				SET @NTIEMPOHOR = @ITIEMPOHOR
				SET @NTIEMPODIA = @ITIEMPODIA
				SET @NTIEMPOSEM = @ITIEMPOSEM
			END
			
		SET @VTIEMPOHOR = CASE WHEN @NTIEMPOHOR > 24 THEN ROUND(@NTIEMPOHOR, 0) ELSE @NTIEMPOHOR END
		SET @VTIEMPODIA = ROUND(@NTIEMPODIA, 0)
		SET @VTIEMPOSEM = CASE WHEN @NTIEMPOSEM >= 1 THEN ROUND(@NTIEMPOSEM, 0) ELSE @ITIEMPOSEM END
		
		SET @NPRECIOHOR = (SELECT TOP 1 [PrecioUnitario] FROM [DemoAlquileresMVC].[dbo].[precio] WHERE [Descripcion] LIKE '%Hora%') * 1.00
		SET @NPRECIODIA = (SELECT TOP 1 [PrecioUnitario] FROM [DemoAlquileresMVC].[dbo].[precio] WHERE [Descripcion] LIKE '%Dia%') * 1.00
		SET @NPRECIOSEM = (SELECT TOP 1 [PrecioUnitario] FROM [DemoAlquileresMVC].[dbo].[precio] WHERE [Descripcion] LIKE '%Semana%') * 1.00
		
		SET @NPRECIOHOR = CAST(@VTIEMPOHOR AS NUMERIC(19,2)) * @NPRECIOHOR * 1.00
		SET @NPRECIODIA = CAST(@VTIEMPODIA AS NUMERIC(19,2)) * @NPRECIODIA * 1.00
		SET @NPRECIOSEM = CAST(@VTIEMPOSEM AS NUMERIC(19,2)) * @NPRECIOSEM * 1.00
		
		SET @NPRECIO = (@NPRECIOHOR + @NPRECIODIA + @NPRECIOSEM)

SELECT @DFECHADESDE
SELECT @DFECHAHASTA
SELECT SEMANA = @VTIEMPOSEM, DIA = @VTIEMPODIA, HORA = @VTIEMPOHOR, PRECIO = @NPRECIO